### ISSUE TITLE
file missed

### ISSUE THREAD

**Issue by ygjwd12345** [MARSLab-UMN/TiltedImageSurfaceNormal#2]
Thanks for you great work.
I face a error:
FileNotFoundError: [Errno 2] No such file or directory: './data/full_2dofa_framenet.pkl'

**Comment by kvuong2711** [comment]
Thanks for pointing it out, it's a mistake from our side while uploading the files. Please follow this link https://tilted-image-normal.s3.amazonaws.com/data_updated.zip to download and extract the updated zip file.

**Comment by ygjwd12345** [comment]
Thanks for your reply. The problem is solved. However, I face another problem.
OSError: ./datasets/scannet-small-frames/scene0554_01/frame-003090-gravity.txt not found.
However, this file is not in scannet-frame-links.txt .
So how can I find these files?

**Comment by ygjwd12345** [comment]
And following the guide by frameNet, the scannet dataset's name should be scannet-frame. Why it becomes to scannet-small-frames?
Does it means you use extra data?

**Comment by ygjwd12345** [comment]
The original scannet dataset doesn't have "gravity.txt". So do you make extra data process before training?

**Comment by kvuong2711** [comment]
Hello, sorry for the late reply.

1) scannet-small-frames is just the downsampled version (240x320) of the data FrameNet provided (480x640). We did this just for own convenience, so you can just modify the paths in the dataset loader to match what you have.

2) Please follow this link https://tilted-image-normal.s3.amazonaws.com/framenet-gravity.zip to download the gravity data. This gravity is the ground-truth gravity direction used for training our network, denoted by "g_hat" in our paper.

**Comment by ygjwd12345** [comment]
> Hello, sorry for the late reply.
> 
> 1. scannet-small-frames is just the downsampled version (240x320) of the data FrameNet provided (480x640). We did this just for own convenience, so you can just modify the paths in the dataset loader to match what you have.
> 2. Please follow this link https://tilted-image-normal.s3.amazonaws.com/framenet-gravity.zip to download the gravity data. This gravity is the ground-truth gravity direction used for training our network, denoted by "g_hat" in ou

**Comment by ygjwd12345** [comment]
it can be run successfully. Thanks for your kind reply.
